from __future__ import annotations

from .color import gradient, hex_to_rgb
from .theme import TerminalTheme


def export_shell_prompt(theme: TerminalTheme, shell: str) -> str:
    shell = shell.lower()
    if shell not in {"bash", "zsh"}:
        raise ValueError("shell must be 'bash' or 'zsh'")

    label = theme.name
    colors = gradient(theme.prompt_gradient, len(label))
    if shell == "bash":
        prefix = "".join(_bash_color(color) + char for color, char in zip(colors, label))
        return "\n".join(
            [
                "# Generated by termforge. Source this file from ~/.bashrc.",
                f"export TERMFORGE_THEME={label!r}",
                f"PS1='{prefix}{_bash_reset()} \\u@\\h:\\w\\$ '",
                "",
            ]
        )

    prefix = "".join(_zsh_color(color) + char for color, char in zip(colors, label))
    return "\n".join(
        [
            "# Generated by termforge. Source this file from ~/.zshrc.",
            f"export TERMFORGE_THEME={label!r}",
            "autoload -Uz colors && colors",
            f"PROMPT='{prefix}{_zsh_reset()} %n@%m:%~%# '",
            "",
        ]
    )


def _bash_color(color: str) -> str:
    r, g, b = hex_to_rgb(color)
    return f"\\[\\033[38;2;{r};{g};{b}m\\]"


def _bash_reset() -> str:
    return "\\[\\033[0m\\]"


def _zsh_color(color: str) -> str:
    r, g, b = hex_to_rgb(color)
    return f"%{{\\033[38;2;{r};{g};{b}m%}}"


def _zsh_reset() -> str:
    return "%{\\033[0m%}"
